/**
 * 世田谷区 子育て支援制度データ
 *
 * 注意: 金額・要件は 2026年7月時点の調査に基づく参考情報です。
 * 制度は年度ごとに改定されるため、必ず url の公式ページで最新情報を確認してください。
 *
 * audience: 対象者（pregnancy: 妊娠中, ages: 子どもの年齢層）→ いずれかに合致すれば対象
 * requires: 追加要件（すべて満たす必要あり。childcare は配列内のいずれか）
 */
const AGE_LABELS = {
  '0-2': '0〜2歳',
  '3-5': '3〜5歳（未就学）',
  elementary: '小学生',
  junior: '中学生',
  high: '高校生年代',
};

const ALL_AGES = ['0-2', '3-5', 'elementary', 'junior', 'high'];

const BENEFITS = [
  {
    id: 'jido-teate',
    name: '児童手当',
    category: '手当・給付金',
    amount: '月額 10,000〜15,000円（第3子以降は30,000円）',
    summary:
      '高校生年代までの児童を養育している方に支給される国の手当です。2024年10月の制度改正により所得制限が撤廃され、支給期間が高校生年代まで延長されました。',
    target: '0歳〜高校生年代（18歳到達後最初の3月31日まで）の児童を養育している方',
    audience: { ages: ALL_AGES },
    requires: {},
    incomeLimit: false,
    window: '子ども家庭課 子ども医療・手当担当（区役所）または各総合支所',
    url: 'https://www.city.setagaya.lg.jp/02413/18187.html',
    documents: [
      '児童手当 認定請求書',
      '振込先口座がわかるもの',
      '申請者の本人確認書類（マイナンバーカード等）',
      '請求者と配偶者のマイナンバーがわかるもの',
      '請求者の健康保険情報がわかるもの（3歳未満の児童がいる場合）',
    ],
    notes: '出生・転入から15日以内の申請で当月分から支給されます（15日特例）。',
  },
  {
    id: 'kodomo-iryohi',
    name: '子ども医療費助成（マル乳・マル子・マル青）',
    category: '医療費助成',
    amount: '保険診療の自己負担分を全額助成（自己負担なし）',
    summary:
      '高校生年代までの子どもの保険診療自己負担分を助成します。世田谷区は所得制限なしで、通院・入院とも自己負担なしで受診できます。',
    target: '0歳〜高校生年代の子どもを養育している区民',
    audience: { ages: ALL_AGES },
    requires: {},
    incomeLimit: false,
    window: '子ども家庭課 子ども医療・手当担当（区役所）または各総合支所',
    url: 'https://www.city.setagaya.lg.jp/kodomokyouiku/kosodate/13019.html',
    documents: [
      '医療証交付申請書',
      '子どもの健康保険情報がわかるもの（資格確認書・保険証等）',
      '申請者の本人確認書類（マイナンバーカード等）',
    ],
    notes: '出生・転入後はできるだけ早く申請してください。医療証は申請月の1日から有効です。',
  },
  {
    id: '018-support',
    name: '018サポート（東京都）',
    category: '手当・給付金',
    amount: '児童1人あたり月額 5,000円（年60,000円）',
    summary:
      '東京都が都内在住の0〜18歳に支給する給付金です。所得制限はありません。申請は東京都のポータルサイトから行います。',
    target: '都内在住の0歳〜18歳の子ども',
    audience: { ages: ALL_AGES },
    requires: {},
    incomeLimit: false,
    window: '東京都（専用ポータルサイトからオンライン申請）',
    url: 'https://018support.metro.tokyo.lg.jp/',
    documents: [
      '申請者の本人確認書類（マイナンバーカード等）',
      '子どもとの関係を確認できる書類（住民票等。マイナンバーカード認証の場合は省略可）',
      '振込先口座がわかるもの',
    ],
    notes: '一度認定されると原則翌年度以降の申請は不要です。新規のお子さんは申請が必要です。',
  },
  {
    id: 'ninpu-kyufu',
    name: '妊婦のための支援給付（妊婦支援給付金）',
    category: '妊娠・出産',
    amount: '1回目 50,000円 ＋ 2回目 胎児1人につき 50,000円',
    summary:
      '2025年4月開始の国の制度で、妊娠届出後と出産前後の2回に分けて給付金が支給されます。従来の出産・子育て応援給付金を引き継ぐ制度です。',
    target: '妊娠の届出をした妊婦の方',
    audience: { pregnancy: true },
    requires: {},
    incomeLimit: false,
    window: '各総合支所 健康づくり課（ネウボラ面接時に案内）',
    url: 'https://www.city.setagaya.lg.jp/02244/20413.html',
    documents: [
      '妊娠届出書（母子健康手帳交付時）',
      '申請者の本人確認書類（マイナンバーカード等）',
      '振込先口座がわかるもの',
    ],
    notes: '妊娠期面接（ネウボラ面接）とあわせて案内されます。',
  },
  {
    id: 'kosodate-riyoken',
    name: 'せたがや子育て利用券',
    category: '妊娠・出産',
    amount: '額面 10,000円分の利用券',
    summary:
      '産前・産後の家事支援、産後ケア、一時預かりなどのサービスに使える世田谷区独自の利用券です。ネウボラ面接（妊娠期面接・産後面接）を受けた方に配付されます。',
    target: '妊婦の方、または2歳までの子どもがいる家庭でネウボラ面接を受けた方',
    audience: { pregnancy: true, ages: ['0-2'] },
    requires: {},
    incomeLimit: false,
    window: '各総合支所 健康づくり課（ネウボラ面接時に配付）',
    url: 'https://www.city.setagaya.lg.jp/02244/1188.html',
    documents: [
      '母子健康手帳',
      '申請者の本人確認書類（マイナンバーカード等）',
    ],
    notes: '面接を受けることが配付の条件です。利用できるサービスは登録事業者一覧をご確認ください。',
  },
  {
    id: 'shussanhi-josei',
    name: '世田谷区出産費助成制度',
    category: '妊娠・出産',
    amount: '出産費用のうち出産育児一時金を超えた額（上限あり）',
    summary:
      '出産費用が健康保険の出産育児一時金を上回った場合に、その差額の一部を区が独自に助成する制度です。',
    target: '出産時に世田谷区に住民登録がある方',
    audience: { pregnancy: true, ages: ['0-2'] },
    requires: {},
    incomeLimit: false,
    window: '子ども家庭課（区役所）',
    url: 'https://www.city.setagaya.lg.jp/02413/1206.html',
    documents: [
      '出産費助成申請書',
      '出産費用の領収書・明細書',
      '出産育児一時金の支給額がわかる書類',
      '振込先口座がわかるもの',
      '申請者の本人確認書類（マイナンバーカード等）',
    ],
    notes: '申請期限があります（出産日から一定期間内）。公式ページで必ずご確認ください。',
  },
  {
    id: 'sango-care',
    name: '産後ケア事業',
    category: '妊娠・出産',
    amount: '利用料の一部助成（ショートステイ・デイケア・訪問型）',
    summary:
      '産後のお母さんと赤ちゃんが、助産師などによる心身のケアや育児サポートを宿泊・日帰り・訪問で受けられる事業です。',
    target: '産後1年未満（サービスにより異なる）のお母さんと赤ちゃん',
    audience: { pregnancy: true, ages: ['0-2'] },
    requires: {},
    incomeLimit: false,
    window: '各総合支所 健康づくり課',
    url: 'https://www.city.setagaya.lg.jp/kodomokyouiku/kosodate/category/12401.html',
    documents: [
      '産後ケア事業利用申請書',
      '母子健康手帳',
    ],
    notes: '妊娠中からの事前申請が可能です。住民税非課税世帯等は利用料の減免があります。',
  },
  {
    id: 'jido-fuyo-teate',
    name: '児童扶養手当',
    category: 'ひとり親支援',
    amount: '月額 約11,000〜46,000円（所得に応じて全部支給／一部支給）',
    summary:
      'ひとり親家庭等の生活の安定と自立を支援する国の手当です。所得に応じて支給額が決まります。',
    target: '18歳到達後最初の3月31日まで（障害がある場合は20歳未満）の児童を養育するひとり親等',
    audience: { ages: ALL_AGES },
    requires: { singleParent: true },
    incomeLimit: true,
    window: '子ども家庭課または各総合支所 子ども家庭支援課',
    url: 'https://www.city.setagaya.lg.jp/kyoutsu/kodomo/1308.html',
    documents: [
      '児童扶養手当 認定請求書',
      '請求者と児童の戸籍謄本（離婚・死別等の事実がわかるもの）',
      '請求者の本人確認書類・マイナンバーがわかるもの',
      '振込先口座がわかるもの',
      '年金手帳など公的年金の受給状況がわかるもの（該当者のみ）',
    ],
    notes: '支給額は毎年度改定されます。申請前に窓口での事前相談をおすすめします。',
  },
  {
    id: 'jido-ikusei-teate',
    name: '児童育成手当（育成手当）',
    category: 'ひとり親支援',
    amount: '児童1人につき月額 13,500円',
    summary:
      '東京都の制度で、ひとり親家庭等の児童を養育している方に支給されます。児童扶養手当とあわせて受給できます。',
    target: '18歳到達後最初の3月31日までの児童を養育するひとり親等（所得制限あり）',
    audience: { ages: ALL_AGES },
    requires: { singleParent: true },
    incomeLimit: true,
    window: '子ども家庭課または各総合支所 子ども家庭支援課',
    url: 'https://www.city.setagaya.lg.jp/kyoutsu/kodomo/1308.html',
    documents: [
      '児童育成手当 認定請求書',
      '請求者と児童の戸籍謄本',
      '請求者の本人確認書類・マイナンバーがわかるもの',
      '振込先口座がわかるもの',
    ],
    notes: '児童扶養手当より所得制限が緩やかです。児童扶養手当が対象外でも受給できる場合があります。',
  },
  {
    id: 'hitorioya-iryohi',
    name: 'ひとり親家庭等医療費助成（マル親）',
    category: 'ひとり親支援',
    amount: '保険診療の自己負担分の全部または一部を助成',
    summary:
      'ひとり親家庭等の親と児童の医療費の自己負担分を助成する制度です（所得制限あり）。',
    target: '18歳到達後最初の3月31日まで（障害がある場合は20歳未満）の児童を養育するひとり親家庭等',
    audience: { ages: ALL_AGES },
    requires: { singleParent: true },
    incomeLimit: true,
    window: '子ども家庭課または各総合支所 子ども家庭支援課',
    url: 'https://www.city.setagaya.lg.jp/kyoutsu/kodomo/1308.html',
    documents: [
      'マル親医療証 交付申請書',
      '請求者と児童の戸籍謄本',
      '健康保険情報がわかるもの（親・児童とも）',
      '請求者の本人確認書類・マイナンバーがわかるもの',
    ],
    notes: '住民税非課税世帯は自己負担なし、課税世帯は一部負担があります。',
  },
  {
    id: 'tokubetsu-jido-fuyo',
    name: '特別児童扶養手当',
    category: '障害のある子どもへの支援',
    amount: '月額 約38,000円（2級）／約57,000円（1級）',
    summary:
      '精神または身体に中程度以上の障害のある20歳未満の児童を養育している方に支給される国の手当です。',
    target: '障害のある20歳未満の児童を養育している方（所得制限あり）',
    audience: { ages: ALL_AGES },
    requires: { disability: true },
    incomeLimit: true,
    window: '子ども家庭課または各総合支所 子ども家庭支援課',
    url: 'https://www.city.setagaya.lg.jp/kyoutsu/kodomo/1308.html',
    documents: [
      '特別児童扶養手当 認定請求書',
      '所定の診断書（障害の種類に応じた様式）または身体障害者手帳・愛の手帳の写し',
      '請求者と児童の戸籍謄本',
      '請求者の本人確認書類・マイナンバーがわかるもの',
      '振込先口座がわかるもの',
    ],
    notes: '支給額は毎年度改定されます。手帳の等級により診断書が省略できる場合があります。',
  },
  {
    id: 'shogaiji-fukushi-teate',
    name: '障害児福祉手当',
    category: '障害のある子どもへの支援',
    amount: '月額 約16,000円',
    summary:
      '重度の障害により日常生活で常時介護を必要とする20歳未満の在宅の児童本人に支給される国の手当です。',
    target: '重度障害のある20歳未満の在宅児童（所得制限あり）',
    audience: { ages: ALL_AGES },
    requires: { disability: true },
    incomeLimit: true,
    window: '各総合支所 保健福祉課',
    url: 'https://www.city.setagaya.lg.jp/kyoutsu/kodomo/1308.html',
    documents: [
      '障害児福祉手当 認定請求書',
      '所定の診断書',
      '児童本人名義の振込先口座がわかるもの',
      '本人確認書類・マイナンバーがわかるもの',
    ],
    notes: '施設入所中の方は対象外です。',
  },
  {
    id: 'jido-ikusei-shogai',
    name: '児童育成手当（障害手当）',
    category: '障害のある子どもへの支援',
    amount: '児童1人につき月額 15,500円',
    summary:
      '東京都の制度で、心身に障害のある20歳未満の児童を養育している方に支給されます。',
    target: '障害のある20歳未満の児童を養育している方（所得制限あり）',
    audience: { ages: ALL_AGES },
    requires: { disability: true },
    incomeLimit: true,
    window: '子ども家庭課または各総合支所 子ども家庭支援課',
    url: 'https://www.city.setagaya.lg.jp/kyoutsu/kodomo/1308.html',
    documents: [
      '児童育成手当（障害手当）認定請求書',
      '身体障害者手帳・愛の手帳の写し、または所定の診断書',
      '請求者の本人確認書類・マイナンバーがわかるもの',
      '振込先口座がわかるもの',
    ],
    notes: 'ひとり親向けの育成手当とは別に、要件を満たせば両方受給できます。',
  },
  {
    id: 'hoikuryo-mushoka',
    name: '幼児教育・保育の無償化／保育料の負担軽減',
    category: '保育・教育',
    amount: '3〜5歳児クラスの保育料無償。0〜2歳児クラスも都の支援により無償化',
    summary:
      '3〜5歳児クラスは国の制度で保育料が無償です。0〜2歳児クラスについても、東京都の第1子保育料無償化（2025年9月開始）により認可保育施設等の保育料が無償化されています。',
    target: '認可保育園・認定こども園等を利用する未就学児',
    audience: { ages: ['0-2', '3-5'] },
    requires: { childcare: ['ninka'] },
    incomeLimit: false,
    window: '保育認定・調整課（区役所）／利用中の施設',
    url: 'https://www.city.setagaya.lg.jp/kodomokyouiku/kosodate/13019.html',
    documents: [
      '子どものための教育・保育給付認定申請書（保育利用申込時）',
      '保護者の就労証明書等（保育の必要性を証明する書類）',
    ],
    notes: '認可施設は原則手続き不要で無償化が適用されます。対象範囲の詳細は公式ページをご確認ください。',
  },
  {
    id: 'ninkagai-hojo',
    name: '認可外保育施設利用者への補助',
    category: '保育・教育',
    amount: '月額上限あり（施設・認定状況により異なる）',
    summary:
      '認証保育所や認可外保育施設を利用する家庭の保育料負担を軽減する補助制度です。無償化の対象施設・上限額は認定状況により異なります。',
    target: '認証保育所・認可外保育施設等を利用する未就学児の保護者',
    audience: { ages: ['0-2', '3-5'] },
    requires: { childcare: ['ninkagai'] },
    incomeLimit: false,
    window: '保育認定・調整課（区役所）',
    url: 'https://www.city.setagaya.lg.jp/kodomokyouiku/kosodate/13019.html',
    documents: [
      '補助金交付申請書',
      '施設等利用給付認定申請書（無償化対象の場合）',
      '保護者の就労証明書等（保育の必要性を証明する書類）',
      '保育料の領収書・在籍証明書',
      '振込先口座がわかるもの',
    ],
    notes: '施設が補助対象かどうかを事前にご確認ください。',
  },
  {
    id: 'yochien-hojo',
    name: '私立幼稚園等園児保護者補助金',
    category: '保育・教育',
    amount: '入園料補助・保育料補助（施設等利用給付とあわせて支給）',
    summary:
      '私立幼稚園に通う園児の保護者に対して、入園料や保育料の一部を補助する制度です。幼児教育無償化（施設等利用費）に区独自の上乗せがあります。',
    target: '私立幼稚園等に在籍する園児（3〜5歳）の保護者',
    audience: { ages: ['3-5'] },
    requires: { childcare: ['yochien'] },
    incomeLimit: false,
    window: '子ども・若者支援課（区役所）／在籍する幼稚園経由',
    url: 'https://www.city.setagaya.lg.jp/kodomokyouiku/kosodate/13019.html',
    documents: [
      '保護者補助金交付申請書（幼稚園経由で配付）',
      '施設等利用給付認定申請書',
      '振込先口座がわかるもの',
    ],
    notes: '多くの手続きは在籍する幼稚園を通じて行います。',
  },
  {
    id: 'byoji-hoiku',
    name: '病児・病後児保育',
    category: '保育・教育',
    amount: '1日あたり定額の利用料（減免制度あり）',
    summary:
      '病気中・病気回復期で集団保育が難しいお子さんを、専用施設で一時的に預かる事業です。事前登録が必要です。',
    target: '区内在住の生後5か月〜小学6年生（施設により異なる）',
    audience: { ages: ['0-2', '3-5', 'elementary'] },
    requires: {},
    incomeLimit: false,
    window: '各実施施設（事前登録制）／保育課',
    url: 'https://www.city.setagaya.lg.jp/kodomokyouiku/kosodate/category/12401.html',
    documents: [
      '病児・病後児保育 利用登録書',
      '医師連絡票（利用時。かかりつけ医が記入）',
      '母子健康手帳・健康保険情報がわかるもの',
    ],
    notes: '利用前の事前登録をおすすめします。予約方法は施設ごとに異なります。',
  },
  {
    id: 'shugaku-enjo',
    name: '就学援助（学用品費・給食費等の援助）',
    category: '保育・教育',
    amount: '学用品費・給食費・移動教室費等の実費相当を援助',
    summary:
      '経済的な理由で就学が困難な小・中学生の保護者に、学用品費や給食費などを援助する制度です。所得基準があります。',
    target: '区立小・中学校等に通う児童・生徒の保護者（所得基準あり）',
    audience: { ages: ['elementary', 'junior'] },
    requires: {},
    incomeLimit: true,
    window: '学務課（教育委員会）／在籍する学校経由',
    url: 'https://www.city.setagaya.lg.jp/kodomokyouiku/kosodate/13019.html',
    documents: [
      '就学援助費 申請書（学校経由で配付）',
      '振込先口座がわかるもの',
    ],
    notes: '毎年度申請が必要です。年度途中でも申請できます。',
  },
];

// Node.js のテストから読み込めるようにエクスポート（ブラウザではグローバル変数）
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { BENEFITS, AGE_LABELS, ALL_AGES };
}
