"""Initial migration

Revision ID: 001
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create orders table
    op.create_table(
        "orders",
        sa.Column("order_id", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column(
            "order_type",
            sa.Enum("SUBSCRIPTION", "ONEOFF", name="ordertype"),
            nullable=False,
        ),
        sa.Column("subscription_id", sa.String(length=50), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "channel",
            sa.Enum("WEB", "MOBILE", "PHONE", "OTHER", name="channel"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_index(op.f("ix_orders_order_id"), "orders", ["order_id"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_orders_order_date"), "orders", ["order_date"], unique=False
    )
    op.create_index(
        op.f("ix_orders_order_type"), "orders", ["order_type"], unique=False
    )
    op.create_index(
        op.f("ix_orders_subscription_id"), "orders", ["subscription_id"], unique=False
    )
    op.create_index(
        "ix_orders_date_type", "orders", ["order_date", "order_type"], unique=False
    )
    op.create_index(
        "ix_orders_user_date", "orders", ["user_id", "order_date"], unique=False
    )

    # Create products table
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("subcategory", sa.String(length=50), nullable=True),
        sa.Column("brand", sa.String(length=50), nullable=True),
        sa.Column("is_set_item", sa.Boolean(), nullable=True),
        sa.Column("base_price", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("cost", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("weight_grams", sa.Integer(), nullable=True),
        sa.Column("dimensions", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("min_order_quantity", sa.Integer(), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("supplier_code", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("sku"),
    )
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=False)
    op.create_index(
        op.f("ix_products_category"), "products", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_products_is_set_item"), "products", ["is_set_item"], unique=False
    )
    op.create_index(op.f("ix_products_active"), "products", ["active"], unique=False)
    op.create_index(
        "ix_products_category_active", "products", ["category", "active"], unique=False
    )
    op.create_index(
        "ix_products_brand_category", "products", ["brand", "category"], unique=False
    )

    # Create subscriptions table
    op.create_table(
        "subscriptions",
        sa.Column("subscription_id", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("frequency_days", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PAUSED", "CANCELLED", name="subscriptionstatus"),
            nullable=False,
        ),
        sa.Column("next_delivery_date", sa.Date(), nullable=True),
        sa.Column("pause_until_date", sa.Date(), nullable=True),
        sa.Column("cancellation_date", sa.Date(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=200), nullable=True),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column("delivery_instructions", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("subscription_id"),
    )
    op.create_index(
        op.f("ix_subscriptions_subscription_id"),
        "subscriptions",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_next_delivery_date"),
        "subscriptions",
        ["next_delivery_date"],
        unique=False,
    )
    op.create_index(
        "ix_subscriptions_user_status",
        "subscriptions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_subscriptions_next_delivery",
        "subscriptions",
        ["next_delivery_date", "status"],
        unique=False,
    )

    # Create user_profiles table
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("customer_segment", sa.String(length=50), nullable=True),
        sa.Column("acquisition_channel", sa.String(length=50), nullable=True),
        sa.Column("registration_date", sa.Date(), nullable=True),
        sa.Column("preferred_delivery_day", sa.String(length=10), nullable=True),
        sa.Column("dietary_restrictions", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=False
    )
    op.create_index("ix_user_profiles_email", "user_profiles", ["email"], unique=False)
    op.create_index(
        "ix_user_profiles_segment", "user_profiles", ["customer_segment"], unique=False
    )

    # Create order_items table (depends on orders and products)
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.String(length=50), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("discount_rate", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("promotion_code", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["products.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False
    )
    op.create_index(op.f("ix_order_items_sku"), "order_items", ["sku"], unique=False)
    op.create_index(
        "ix_order_items_sku_date", "order_items", ["sku", "created_at"], unique=False
    )
    op.create_index(
        "ix_order_items_order_sku", "order_items", ["order_id", "sku"], unique=False
    )

    # Create inventory_snapshots table (depends on products)
    op.create_table(
        "inventory_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("on_hand_quantity", sa.Integer(), nullable=False),
        sa.Column("allocated_quantity", sa.Integer(), nullable=False),
        sa.Column("available_quantity", sa.Integer(), nullable=False),
        sa.Column("inbound_quantity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["products.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_date", "sku", name="uq_inventory_snapshots_date_sku"
        ),
    )
    op.create_index(
        op.f("ix_inventory_snapshots_snapshot_date"),
        "inventory_snapshots",
        ["snapshot_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_snapshots_sku"), "inventory_snapshots", ["sku"], unique=False
    )
    op.create_index(
        "ix_inventory_snapshots_date_sku",
        "inventory_snapshots",
        ["snapshot_date", "sku"],
        unique=False,
    )

    # Create product_sets table (depends on products)
    op.create_table(
        "product_sets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("set_sku", sa.String(length=100), nullable=False),
        sa.Column("component_sku", sa.String(length=100), nullable=False),
        sa.Column("component_quantity", sa.Integer(), nullable=False),
        sa.Column("is_optional", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["component_sku"],
            ["products.sku"],
        ),
        sa.ForeignKeyConstraint(
            ["set_sku"],
            ["products.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "set_sku", "component_sku", name="uq_product_sets_sku_component"
        ),
    )
    op.create_index(
        "ix_product_sets_set_sku", "product_sets", ["set_sku"], unique=False
    )

    # Add foreign key constraint to orders table
    op.create_foreign_key(
        None, "orders", "subscriptions", ["subscription_id"], ["subscription_id"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign key constraints
    op.drop_constraint(None, "orders", type_="foreignkey")

    # Drop tables in reverse order
    op.drop_table("product_sets")
    op.drop_table("inventory_snapshots")
    op.drop_table("order_items")
    op.drop_table("user_profiles")
    op.drop_table("subscriptions")
    op.drop_table("products")
    op.drop_table("orders")

    # Drop custom types
    op.execute("DROP TYPE IF EXISTS subscriptionstatus")
    op.execute("DROP TYPE IF EXISTS channel")
    op.execute("DROP TYPE IF EXISTS ordertype")

    # ### end Alembic commands ###
